//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDIEMHP
    {
        public int ID { get; set; }
        public string MaSV { get; set; }
        public string MaHP { get; set; }
        public Nullable<double> DiemHP { get; set; }
    
        public virtual DMHOCPHAN DMHOCPHAN { get; set; }
        public virtual DMSINHVIEN DMSINHVIEN { get; set; }
    }
}
