//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMHOCPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMHOCPHAN()
        {
            this.DMDIEMHPs = new HashSet<DMDIEMHP>();
        }
    
        public string MaHP { get; set; }
        public string TenHP { get; set; }
        public Nullable<int> Sodvht { get; set; }
        public string MaNganh { get; set; }
        public Nullable<int> HocKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMDIEMHP> DMDIEMHPs { get; set; }
        public virtual DMNGANH DMNGANH { get; set; }
    }
}
