//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMLOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMLOP()
        {
            this.DMSINHVIENs = new HashSet<DMSINHVIEN>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string MaNganh { get; set; }
        public Nullable<int> KhoaHoc { get; set; }
        public string HeDT { get; set; }
        public Nullable<int> NamNhapHoc { get; set; }
    
        public virtual DMNGANH DMNGANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMSINHVIEN> DMSINHVIENs { get; set; }
    }
}
